In [6]:
import pandas as pd
import numpy as np

In [53]:
df = pd.read_excel('KPMG_VI_New_raw_data_update_final.xlsx')
df.head()

,Unnamed: 0,Note: The data and information in this document is reflective of a hypothetical situation and client. This document is to be used for KPMG Virtual Internship purposes only.,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,KPMG Virtual Internship,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Sprocket Central Pty Ltd Data Set,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df.iloc[0:50]

,Unnamed: 0,Note: The data and information in this document is reflective of a hypothetical situation and client. This document is to be used for KPMG Virtual Internship purposes only.,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,KPMG Virtual Internship,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Sprocket Central Pty Ltd Data Set,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,"To view the datasets, click on the yellow tabs...",NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,"Click on the sheets are named ""CustomerDemogra...",NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,Module 1 Task,NaN,NaN,Module 2 Task,NaN,NaN,Module 3 Task
11,NaN,NaN,Your task is to take a look at the following d...,NaN,NaN,Create a PowerPoint presentation wihch outline...,NaN,NaN,Please develop a dashboard that we can present...
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,Return to the virtual internship here:,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,https://www.insidesherpa.com/virtual-internshi...,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,"© 2018 KPMG, an Australian partnership and a m...",NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,"Need some help getting started, or new to exce...",NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,Here is a warm up task with this dataset,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,Warm up task:,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,1) Look over the datasets provided by Sprocket...,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,2) Go to the 'CustomerDemographic' dataset,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,3) Select entire dataset by clicking cell in t...,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,"4) Once you've selected the entire dataset, cl...",NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df.iloc[50:100]

,Unnamed: 0,Note: The data and information in this document is reflective of a hypothetical situation and client. This document is to be used for KPMG Virtual Internship purposes only.,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,5) Go to the 'DOB' column and click the filter...,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,NaN,NaN,6) Now do you notice anything strange about th...,NaN,NaN,NaN,NaN,NaN,NaN
94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,"7) For the rest of this Module 1 task, it is u...",NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
rows_to_drop = [0,1,2,5,8,9,12,13,14,12,13,14,17,18,20,21,24,25,30,31,32,33,34,35,36,37,38,39,40,41,42,
                43,44,45,46,47,49,50,51,52,53,54,55,56,57,58,59,60,62,63,64,65,66,67,68,69,70,71,72,73,
                74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,94,95,96]
df.drop(rows_to_drop, inplace=True)

In [55]:
df

,Unnamed: 0,Note: The data and information in this document is reflective of a hypothetical situation and client. This document is to be used for KPMG Virtual Internship purposes only.,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
3,NaN,NaN,KPMG Virtual Internship,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Sprocket Central Pty Ltd Data Set,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,"To view the datasets, click on the yellow tabs...",NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,"Click on the sheets are named ""CustomerDemogra...",NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,Module 1 Task,NaN,NaN,Module 2 Task,NaN,NaN,Module 3 Task
11,NaN,NaN,Your task is to take a look at the following d...,NaN,NaN,Create a PowerPoint presentation wihch outline...,NaN,NaN,Please develop a dashboard that we can present...
15,NaN,NaN,Return to the virtual internship here:,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,https://www.insidesherpa.com/virtual-internshi...,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,"© 2018 KPMG, an Australian partnership and a m...",NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,"Need some help getting started, or new to exce...",NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,Here is a warm up task with this dataset,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,Warm up task:,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,1) Look over the datasets provided by Sprocket...,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,2) Go to the 'CustomerDemographic' dataset,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,3) Select entire dataset by clicking cell in t...,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,"4) Once you've selected the entire dataset, cl...",NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,5) Go to the 'DOB' column and click the filter...,NaN,NaN,NaN,NaN,NaN,NaN
93,NaN,NaN,6) Now do you notice anything strange about th...,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,"7) For the rest of this Module 1 task, it is u...",NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
array1 = df["Unnamed: 2"].values
array1

array(['KPMG Virtual Internship', 'Sprocket Central Pty Ltd Data Set',
       'To view the datasets, click on the yellow tabs/sheets at the bottom of this file',
       'Click on the sheets are named "CustomerDemographic", "CustomerAddress", "Transactions" and "NewCustomerList"',
       'Module 1 Task',
       "Your task is to take a look at the following datasets provided by Sprocket Central Pty Ltd and identify all data quality issues. Once you've had a look at these datasets, draft an email to the client identifying all data quality issues. ",
       'Return to the virtual internship here:',
       'https://www.insidesherpa.com/virtual-internships/theme/m7W4GMqeT3bh9Nb2c/KPMG-Data-Analytics-Virtual-Internship',
       '© 2018 KPMG, an Australian partnership and a member firm of the KPMG network of independent member firms affiliated with KPMG International Cooperative (“KPMG International”), a Swiss entity. All rights reserved.',
       'Need some help getting started, or new to excel/data?',
       'Here is a warm up task with this dataset', 'Warm up task:',
       '1) Look over the datasets provided by Sprocket Central Pty Ltd (you can navigate through sheets by clicking the tabs at the bottom). ',
       "2) Go to the 'CustomerDemographic' dataset",
       '3) Select entire dataset by clicking cell in the uppermost top left hand corner (see picture below)',
       "4) Once you've selected the entire dataset, click 'Data' in the top bar of the sheet and click 'Filter' (see picture below). Once you click this, you'll notice that arrows appear in each cell in the top row. If you click the arrows, this creates a pop-up which allows you to only select certain values. Make sure you understand how to use the 'Filter' tool properly as this will be your main tool for analysis in the later modules. ",
       "5) Go to the 'DOB' column and click the filter arrow. This should bring up a pop-up which allows you to sort your data. Click 'Ascending' and this should sort your data-set from least to most recent from top to bottom (by date of birth). Once you do this, your data set should look exactly the same as the picture below ",
       "6) Now do you notice anything strange about the data? If you have a look at the first customer (Jephthah Bachmann, you'll notice that they were born in 1843, meaning that they are 175 years old! This is obviously an error in the data so it would be something you'd include in the email to the client.",
       "7) For the rest of this Module 1 task, it is up to you to look through the client datasets and identify problems like in the example above with the DOB. We recommend you dot point everything you find in a Word Document before drafting your email. It is also really important that you use the 'Data Quality Framework Table' (you can find this back in the module page in the 'Resources' section). Note that the parameters and criteria provided to you is vague because this is reflective of what happens in the real world. We encourage you to use other sources like Google and Youtube to help you with this task. Even if you're unsure about the quality of your final email, just give it a go, submit the task and you'll get to see model work which is an actual email that a KPMG Data Analyst has submitted!"],
      dtype=object)

In [59]:
array2 = df["Unnamed: 5"].values
array2

array([nan, nan, nan, nan, 'Module 2 Task',
       'Create a PowerPoint presentation wihch outlines the approach we will be taking to identify which of the 1000 customers Sprocket Central Pty Ltd should target, based on this dataset. Explain the three phases:  Data Exploration; Model Development and Interpretation.',
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
      dtype=object)

In [60]:
array3 = df["Unnamed: 8"].values
array3

array([nan, nan, nan, nan, 'Module 3 Task',
       "Please develop a dashboard that we can present to the client at our next meeting. Display your data summary and results of the analysis in a dashboard (see tools/references for assistance). Specifically, your presentation should specify who Sprocket Central Pty Ltd' should be targeting out of the new 1000 customer list. \n",
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
      dtype=object)

Writing the Instructions clearly for the the reader to be able to read